### ISSUE TITLE
I am trying to get the demo project working on my Mac

### ISSUE THREAD

**Issue by ristkof** [keeshux/tunnelkit#309]
I am trying to get the demo project working on my Mac. At first I got a very basic error saying "Keychain failure: add", which corresponds to `KeychainError.add` in the Keychain.set method.

My system is Mac OS 13.2.

I traced down the issue to this change https://github.com/ristkof/tunnelkit/commit/5c01047249bd8160c423b2a0da5d96d1b6b05bad, which fixes setting the keychain password. But, this flag is probably required to make the TunnelKit work, see https://github.com/passepartoutvpn/tunnelkit/pull/200/commits/433e3f8dc90bf36d4a734c5282ed2f0b8f0926a9

The error code that is returned from the system on the Keychain `SecItemAdd` call is -34018, which led me to this post: https://developer.apple.com/forums/thread/130264 but the links to the available solutions on that page have died in the mean time.

Any ideas on how to get this working? Any documentation available? Thanks.

**Comment by keeshux** [comment]
Let’s start with saying tha,  if the main app works -nobody reported this in months since Ventura release-, this is not an issue. At most, there might be an issue with the demo, but I sense you might have an issue with your entitlements instead.

I can leave the conversation open, but I’m closing this as non-issue.

**Comment by ristkof** [comment]
Thanks @keeshux I think you're right. I think my Application Identifiers were probably setup wrongly with "Automatic Code Signing". I went through the process of manually setting them up, and that seems to have fixed the issue.
