### ISSUE TITLE
Unable to connect through DEMO project's.

### ISSUE THREAD

**Issue by kokitang** [keeshux/tunnelkit#50]
# Summary

### Steps to reproduce
1. Download all files
2. Pod install
3. Change Project's Capabilities as ReadMe.md mentioned.
4. Run 
5. Change nothing and click Connect on device.

### What is the current bug behavior?
Crash.
![image](https://user-images.githubusercontent.com/17448093/49269108-3a01b280-f49e-11e8-8540-6cd3692d96af.png)

### What is the expected correct behavior?
Connect Successfully

------------
Is the demo server not work and must connect to my vpn server by editing the CA and user infos?

**Comment by kokitang** [comment]
Sorry, I was not configured keychain sharing properly.

But after the configuration, the project can run, but still can't connect, for both sample demo data / my server OpenVPN setting.

What I get from log is:

![image](https://user-images.githubusercontent.com/17448093/49386468-909b1500-f75a-11e8-9a1e-e4c064533e3d.png)

**Comment by kokitang** [comment]
I found that 

```
let session = self.currentManager?.connection as! NETunnelProviderSession
            do {
                try session.startTunnel()
            } catch let e {
                print("error starting tunnel: \(e)")
            }
```

doesn't enter the override startTunnel() method of TunnelKitProvider. 
I have no idea about that. 
Do I missed any setting?

**Comment by kokitang** [comment]
![image](https://user-images.githubusercontent.com/17448093/49492115-f3db9300-f891-11e8-8fb4-f149d9eb39a0.png)

I got this log from macOS Console App, do you have any idea about this error?

**Comment by keeshux** [comment]
I'm afraid that the root cause is way above in the log.

**Comment by kokitang** [comment]
Any direction to find out the root cause?

**Comment by keeshux** [comment]
I meant that you should scroll up the console. :-)

Exact steps:

- Disconnect
- Clean up the console
- Connect (it will disconnect shortly after)
- Scroll the console up to the first lines

**Comment by keeshux** [comment]
I read `Failed to find process for koki.ios.demo.BasicTunnel`.

Double check your bundle identifiers in:

- `Info.plist`
- Entitlements
- `ViewController.swift`

in all targets and make sure they all match perfectly.

**Comment by kokitang** [comment]
Oh thank you for help!!
I find the issue finally!

I misunderstood the `bundleIdentifier` variable's meaning.
I thought it is the bundle identifier of the main target, but it actually is the bundle identifier of the Extension.
