### ISSUE TITLE
SocketType' is not a member type of 'TunnelKitProvider

### ISSUE THREAD

**Issue by shahidge4** [keeshux/tunnelkit#52]
Dear, i am  getting following Error
SocketType' is not a member type of 'TunnelKitProvider 

![image](https://user-images.githubusercontent.com/33451088/49435151-badee800-f7d7-11e8-93da-80b04c424cd8.png)

**Comment by keeshux** [comment]
Easily solved, I moved that class outside to the global scope. Upgrade the library (`git pull`) and use `SocketType` without the `TunnelKitProvider` prefix.
