### ISSUE TITLE
Traffic always passes through tunnel

### ISSUE THREAD

**Issue by shahidge4** [keeshux/tunnelkit#55]
Dear i have disabled **push "redirect-gateway def1"** in server Side but all traffic is still  passing through the tunnel.

**Comment by keeshux** [comment]
The option is not currently supported.

**Comment by shahidge4** [comment]
or how we get replay messages send by server

**Comment by keeshux** [comment]
https://github.com/keeshux/tunnelkit/blob/7179d6471cd12a8ab7cfa9510acc56c5048f6897/TunnelKit/Sources/AppExtension/TunnelKitProvider.swift#L465

The issue is otherwise clear (low priority), so please don't clutter the thread unless you can provide a PR. Issues are not meant to request support.

**Comment by keeshux** [comment]
My bad, #90 was a duplicate. This is fixed in `master`.
