### ISSUE TITLE
Packet authentication failure with tls-auth

### ISSUE THREAD

**Issue by oguzklc** [keeshux/tunnelkit#61]
Cannot connect to vpn with ovpn file. I use ConfigurationParser class to parse client.ovpn file and it can parse this file. However, connection cannot be established. Logs are below when try to establish connection : 

2019-02-01 11:47:30.795 INFO TunnelKitProvider.startTunnel():179 - Starting tunnel...
2019-02-01 11:47:30.817 INFO TunnelKitProvider+Configuration.print():459 - 	Protocols: [TCP:1198]
2019-02-01 11:47:30.817 INFO TunnelKitProvider+Configuration.print():460 - 	Cipher: AES-256-CBC
2019-02-01 11:47:30.817 INFO TunnelKitProvider+Configuration.print():461 - 	Digest: HMAC-SHA1
2019-02-01 11:47:30.817 INFO TunnelKitProvider+Configuration.print():465 - 	Client verification: disabled
2019-02-01 11:47:30.817 INFO TunnelKitProvider+Configuration.print():467 - 	MTU: 1350
2019-02-01 11:47:30.818 INFO TunnelKitProvider+Configuration.print():468 - 	Compression framing: comp-lzo
2019-02-01 11:47:30.818 INFO TunnelKitProvider+Configuration.print():472 - 	Keep-alive: never
2019-02-01 11:47:30.818 INFO TunnelKitProvider+Configuration.print():477 - 	Renegotiation: never
2019-02-01 11:47:30.819 INFO TunnelKitProvider+Configuration.print():480 - 	TLS wrapping: auth
2019-02-01 11:47:30.819 INFO TunnelKitProvider+Configuration.print():484 - 	Debug: true

2019-02-01 11:47:31.132 ERROR SessionProxy.loopLink():419 - Failed LINK read: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"

2019-02-01 11:47:31.209 ERROR TunnelKitProvider.finishTunnelDisconnection():296 - Tunnel did stop (error: linkError)

Server errors are below : 

Thu Jan 31 16:53:11 2019 TCP connection established with [AF_INET]xxx.xx.xxx.xx:xxxx
Thu Jan 31 16:53:11 2019 xxx.xx.xxx.xx:xxxx TLS: Initial packet from [AF_INET]xxx.xx.xxx.xx:xxxx, sid=3b85a451 fe3ffe6a
Thu Jan 31 16:53:12 2019 xxx.xx.xxx.xx:xxxx Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #12 / time = (1548942796) Thu Jan 31 $
Thu Jan 31 16:53:12 2019 xxx.xx.xxx.xx:xxxxTLS Error: incoming packet authentication failed from [AF_INET]xxx.xx.xxx.xx:xxxx
Thu Jan 31 16:53:12 2019 xxx.xx.xxx.xx:xxxx Fatal TLS error (check_tls_errors_co), restarting
Thu Jan 31 16:53:12 2019 xxx.xx.xxx.xx:xxxx SIGUSR1[soft,tls-error] received, client-instance restarting

**Comment by rodrigocasillas** [comment]
Same with me

**Comment by oguzklc** [comment]
I use this client.ovpn file on OpenVPN app and can connect to vpn without any problem. However, I cannot connect to vpn with this code. I use ConfigurationParser to parse client.ovpn file and it can parse.

**Comment by oguzklc** [comment]
I sent an email to website@davidederosa.com. This mail include client.ovpn file, username and password.

**Comment by keeshux** [comment]
As usual, also make sure that the server has compression disabled. ATM I can't recall if compression may be involved in the handshake too, even though I tend to believe it's not. Better double check regardless.

**Comment by ms-tii** [comment]
@keeshux Hello Sir,
I am trying to connect vpn with .ovpn file and unable to use ConfigurationParser class to parse client.ovpn file in demo project. For this I create extension in view controller class - 

extension ViewController {
    private static let bundleIdentifier = "it.****.VPNProject.VPNProjectTunnel"

    private func makeProtocol() -> NETunnelProviderProtocol {


        guard let configurationFileURL = Bundle.main.url(forResource: "client", withExtension: "ovpn"),
            let configurationFileContent = try? Data(contentsOf: configurationFileURL)
            else {
                fatalError()
        }

        let tunnelProtocol = NETunnelProviderProtocol()
        tunnelProtocol.serverAddress = "32.46.32.239"
        tunnelProtocol.providerBundleIdentifier = ViewController.bundleIdentifier
        tunnelProtocol.providerConfiguration = ["ovpn": configurationFileContent]
        return tunnelProtocol
    }
}

and by using this I am getting this response :-
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 3
VPNStatusDidChange: 3
VPNStatusDidChange: 3 (what is mean of status 1,2,3,4,5 ?)

then in updateButton() method .connected case is called. But in device no vpn icon is shown and also my ip address is not changed.

I didn't understand  what to do now. Please help me
Also I want to know how can I use configurationParser class to parse client.ovpn file in view controller.
![Screenshot 2019-03-13 at 11 23 55 AM](https://user-images.githubusercontent.com/43948059/54257526-a2742b80-4585-11e9-9725-eac5d9d586b3.png)

**Comment by keeshux** [comment]
It's al good (3 = connected) except you must use a physical device, this won't work on the simulator.

**Comment by keeshux** [comment]
@ms-tii open a new issue then I'll delete your comment.

**Comment by ms-tii** [comment]
> @ms-tii open a new issue then I'll delete your comment.
Thanks for the reply, I opened the new issue and you can delete these comments now.

**Comment by keeshux** [comment]
@oguzklc any update?

**Comment by keeshux** [comment]
@oguzklc do you believe this is a duplicate? https://github.com/keeshux/tunnelkit/issues/88

**Comment by wfs498121294** [comment]
same with me

**Comment by qq5050595531** [comment]
same error,how to fix it
