### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by rodrigocasillas** [keeshux/tunnelkit#63]
Hello keeshux perhaps you already know my name from your (github) passepartout issues. Any way I've decided to implement this project since it made more sense. I've managed to compile the demo project. Also have struggled with some issues but could solve them. 
That said I ran unto this issue and wanted to consult with you, hopefully you can advice me in some way. Thank you in advance!

Connect button changes to Disconnect but after a few seconds it comes back to Connect.

Xcode logs:
![captura de pantalla 2019-02-18 a la s 20 40 32](https://user-images.githubusercontent.com/39197885/52986605-b9c45c80-33bd-11e9-985a-5dda8663e61e.png)

Mac Console App:
![captura de pantalla 2019-02-18 a la s 20 02 11](https://user-images.githubusercontent.com/39197885/52985452-7c5dd000-33b9-11e9-9782-2023699ace49.png)

**Comment by rodrigocasillas** [comment]
Hi Keeshux It would be great to have some advice from you on what could this problem be. Im using ConfigurationParser Thanks!.
I've also sent an email to website@davidederosa.com hope you can reach out.

![captura de pantalla 2019-02-27 a la s 13 04 56](https://user-images.githubusercontent.com/39197885/53515979-d84ae780-3a90-11e9-923c-aebd68979507.png)

**Comment by keeshux** [comment]
Can you please STOP spamming me everywhere? I will have to start deleting messages otherwise. Be cool with people's time. Thank you.

**Comment by keeshux** [comment]
Also, had you read my former messages, I had told you that this is a DNS problem on your end. So this issue will be closed and I beg you don't re-open it or open a new one until you get your network right.
