### ISSUE TITLE
OpenSSL-Apple problem after pod install

### ISSUE THREAD

**Issue by xixlolz** [keeshux/tunnelkit#66]
# Summary
When adding pod 'TunnelKit'  to my pod file and afterwards running pod install either the process enters an infinite sleep/grep loop or throws xcrun: error: SDK "iphoneos" cannot be located
### Steps to reproduce
run pod install
### What is the current bug behavior?
enters an infinite sleep/grep loop or throws xcrun: error: SDK "iphoneos" cannot be located
### What is the expected correct behavior?
should install tunnelkit

**Comment by keeshux** [comment]
Can you try explicitly?

    pod 'OpenSSL-Apple', '~> 1.1.0i.2'

**Comment by xixlolz** [comment]
Yes I tried and it worked, thank you for your quick response.

**Comment by keeshux** [comment]
What version of TunnelKit do you see in the Podfile.lock?

**Comment by xixlolz** [comment]
It's version 1.4.2

**Comment by keeshux** [comment]
I'm taking an internal note but closing this as the issue was eventually fixed.

**Comment by bemomilib** [comment]
I'm having the same problem, but the solution mentioned here, did not work for me. I'd be grateful for your help. 🙏🙏🙏
