### ISSUE TITLE
Unable to connect with client.ovpn file in demo project(status is 3)

### ISSUE THREAD

**Issue by ms-tii** [keeshux/tunnelkit#68]
![Screenshot 2019-03-13 at 11 23 55 AM](https://user-images.githubusercontent.com/43948059/54272279-5d61f080-45a9-11e9-92d5-483aa0d06c7f.png)

@keeshux  Hello Sir,
I am trying to connect vpn with .ovpn file and unable to use ConfigurationParser class to parse client.ovpn file in demo project. For this I create extension in view controller class -

extension ViewController {
private static let bundleIdentifier = "it.****.VPNProject.VPNProjectTunnel"

private func makeProtocol() -> NETunnelProviderProtocol {

    guard let configurationFileURL = Bundle.main.url(forResource: "client", withExtension: "ovpn"),
        let configurationFileContent = try? Data(contentsOf: configurationFileURL)
        else {
            fatalError()
    }

    let tunnelProtocol = NETunnelProviderProtocol()
    tunnelProtocol.serverAddress = "32.46.32.239"
    tunnelProtocol.providerBundleIdentifier = ViewController.bundleIdentifier
    tunnelProtocol.providerConfiguration = ["ovpn": configurationFileContent]
    return tunnelProtocol
}
}

and by using this I am getting this response :-
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 3
VPNStatusDidChange: 3
VPNStatusDidChange: 3 (what is mean of status 1,2,3,4,5 ?)

then in updateButton() method .connected case is called. But in device no vpn icon is shown and also my ip address is not changed.I am using physical device iPhone6 plus and 8 plus, not an simulator.

I didn't understand what to do now. Please help me
Also I want to know how can I use configurationParser class to parse client.ovpn file in view controller.From the documentation it not easy to understand the steps.

**Comment by keeshux** [comment]
You're creating `NETunnelProviderProtocol` the wrong way, you must use `TunnelKitProvider.ConfigurationBuilder` instead. The demo has a fully working sample code, it's no more than a copy & paste.

**Comment by ms-tii** [comment]
@keeshux Hi, thanks for the reply,

I do with configuration parser in viewController extension like this

guard let confiUrl = Bundle.main.url(forResource: "client", withExtension: "ovpn") else {
            print("File not found")
            fatalError()
        }
        
        
        do {
            let configurationFileContent =  try ConfigurationParser.parsed(fromURL: confiUrl)
            let builder = TunnelKitProvider.ConfigurationBuilder(sessionConfiguration: configurationFileContent.configuration)
            
            let configuration = builder.build()
            return try! configuration.generatedTunnelProtocol(withBundleIdentifier: ViewController.bundleIdentifier, appGroup: ViewController.appGroup, hostname: "32.46.32.239")
        }
        catch let error as NSError {
       }

But getting same response as previously I got vpn status == 3, and not actually connected in device.Also in the device's VPN setting it shows connected.

Please help me 
![Screenshot 2019-03-14 at 11 58 28 AM](https://user-images.githubusercontent.com/43948059/54336414-02d09f00-4652-11e9-84a7-e2177b25cf1e.png)

**Comment by ms-tii** [comment]
![Screenshot 2019-03-14 at 11 58 28 AM](https://user-images.githubusercontent.com/43948059/54340275-0289d100-465d-11e9-9ccc-c4cc39eefbb8.png)

@keeshux  Hello Sir, Thanks for the reply
I do also with ConfigurationParser and TunnelKitProvider.ConfigurationBuilder. Bellow is the method I use:- 
private func makeProtocol() -> NETunnelProviderProtocol {
        guard let confiUrl = Bundle.main.url(forResource: "client", withExtension: "ovpn") else {
            print("File not found")
            fatalError()
        }
        do {
            let configurationFileContent =  try ConfigurationParser.parsed(fromURL: confiUrl)
            let builder = TunnelKitProvider.ConfigurationBuilder(sessionConfiguration: configurationFileContent.configuration)
            
            let configuration = builder.build()
            return try! configuration.generatedTunnelProtocol(withBundleIdentifier: ViewController.bundleIdentifier, appGroup: ViewController.appGroup, hostname: "32.46.32.239")
        }
        catch let error as NSError {
            print(error.localizedDescription)
        }
}

But getting same response as previously. It also shows connected in device's VPN settings but actually not working. See the attached picture.

Please help me

- Mohit ms@tii.co.in

**Comment by keeshux** [comment]
Try "Delete VPN" then restart the device.

**Comment by ms-tii** [comment]
> Try "Delete VPN" then restart the device.

Nothing reflect :(

**Comment by keeshux** [comment]
Do you happen to have any "Personal VPN" configured? Could you post a screenshot of "Settings > VPN"?

**Comment by keeshux** [comment]
I guess the fastest way is that you send me your whole project code. Use the email you'll find here on GitHub.

**Comment by ms-tii** [comment]
This is not resolved yet, why you closed it ?

And I can't send you my client.ovpn file as I have no authority to share it with others. If I send you my whole project without .ovpn file, Can you able to figure out the issue?

**Comment by keeshux** [comment]
Yeah I don't need the .ovpn

**Comment by ms-tii** [comment]
I have sent the email to you at website@davidederosa.com.

**Comment by ms-tii** [comment]
Unable to send you zip file of the project by email at website@davidederosa.com

**Comment by keeshux** [comment]
> Unable to send you zip file of the project by email at [website@davidederosa.com](mailto:website@davidederosa.com)

Unfortunately there is not much I can do without it.

**Comment by manveersinghdodiya** [comment]
Can we connect open vpn with this demo? I am testing with open vpn server and getting the same response as about. 
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 2
VPNStatusDidChange: 3
VPNStatusDidChange: 3
