### ISSUE TITLE
I am not able to compile with xcode 10.1

### ISSUE THREAD

**Issue by moldis** [keeshux/tunnelkit#89]
# Summary

I am receiving bench of errors and can't compile

### Steps to reproduce

Just open with xcode version 10.1 and swift 5

### Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/2959408/56458958-74b9a800-63b7-11e9-92d1-f262c9f7c859.png)

**Comment by keeshux** [comment]
None of this on `master` with Xcode 10.2, both library and demo projects. Are you sure you're up to date with `master`? Give more details about your environment.

**Comment by moldis** [comment]
Yes, i am in master branch for sure. 

I am trying to compile with Xcode 10.1 and Toolchain: Swift 5.0 Snapshot 2018-12-09 (a)
MacOs Mojave 10.14.4

Do you need any other info ?

**Comment by keeshux** [comment]
How are you using the library? Pod? Copy/paste? This Xcode project? The Demo project? Your project?

**Comment by moldis** [comment]
In my project I added Pods, with this lines:
def shared_pods
  pod 'TunnelKit', :git => 'https://github.com/keeshux/tunnelkit'
  pod 'TunnelKit/LZO', :git => 'https://github.com/keeshux/tunnelkit'
  pod 'SSZipArchive'
end

abstract_target 'iOS' do
    platform :ios, '11.0'
   shared_pods
end

then command pod install - it successfully installed and shown in my pods folder.

Then i building project - it shows me errors below

**Comment by moldis** [comment]
Just tried to download Demo project from scratch and still getting same issue

**Comment by keeshux** [comment]
Then it might well be Xcode, they tend to mess up with Swift updates. You might want to upgrade to 10.2 and if that's the issue I'll update the README requirements accordingly.

Anyway, you'd better attach a .zip of your test project.

**Comment by moldis** [comment]
Actually i just using Demo project form your git repo. I will try to update to 10.2 as i downgrade library to 1 month ago and it looks works fine (it is around 1.5.2 version).

**Comment by moldis** [comment]
And i have one more question as well. When i upload my app to appstore - apple rejecting it bcz of this framework and app crashing with this error: 
Termination Description: DYLD, Library not loaded: openssl.dylib

Note: this happens only when upload to App Store, in local environment it works fine, same if i remove library and upload it again - it works fine

Is there something inside, that apple don't like ?

**Comment by keeshux** [comment]
> And i have one more question as well. When i upload my app to appstore - apple rejecting it bcz of this framework and app crashing with this error:
> Termination Description: DYLD, Library not loaded: openssl.dylib
> 
> Note: this happens only when upload to App Store, in local environment it works fine, same if i remove library and upload it again - it works fine
> 
> Is there something inside, that apple don't like ?

IIRC you should disable Bitcode. Recompiling the library seems to mess up with addressing.

**Comment by keeshux** [comment]
> Actually i just using Demo project form your git repo. I will try to update to 10.2 as i downgrade library to 1 month ago and it looks works fine (it is around 1.5.2 version).

If 1.5.2 is working (Swift 4.2), then you're probably not using Swift 5 in the relevant part of your project, i.e. the one depending on TunnelKit.

**Comment by keeshux** [comment]
Ping @moldis or I'll have to close this.

**Comment by keeshux** [comment]
Also, see #51 for my comment about Bitcode.
