### ISSUE TITLE
Unable to request logs (Unexpectedly found nil while unwrapping an Optional value)

### ISSUE THREAD

**Issue by jsididris** [keeshux/tunnelkit#93]
# Summary
I'm trying the example iOS project provided in this repo with my own OpenVPN server, but the connection didn't work and when i'm trying to display logs to get more details i'm getting crash because of `Unexpectedly found nil while unwrapping an Optional value`.

### Steps to reproduce
Using demo project into real iPhone 6 (iOS 11) device, taping "Connect" and then "See log".

### What is the current bug behavior?

It seem that the `data` variable can't be unwrapped due to his `nil` value, here: https://github.com/keeshux/tunnelkit/blob/master/Demo/BasicTunnel-iOS/ViewController.swift#L222

### Relevant logs and/or screenshots

<img width="1680" alt="Capture d’écran 2019-04-27 à 20 49 27" src="https://user-images.githubusercontent.com/27036652/56853878-0c764380-692e-11e9-8f86-58a8c7cf08e2.png">

**Comment by keeshux** [comment]
Most probably an entitlement issue. Ensure that you have properly configured your App Groups and Entitlements in both app and extension with your own bundle identifiers.

**Comment by jsididris** [comment]
Right, thanks I have solved the problem.
